language: c

sudo: required

dist: trusty # Ubuntu 14.04.

compiler:
  - clang
  - gcc

env:
  - DEBUG=0 MPI=0
  - DEBUG=0 MPI=1
  - DEBUG=1 MPI=0
  - DEBUG=1 MPI=1

addons:
  apt:
    # Travis whitelist of packages.
    # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    packages:
      - cmake
      - gcc
      - clang
      - libopenmpi-dev
      - gfortran

  artifacts:
    # We stick build artifacts onto Amazon S3 so that they can be retrieved 
    # either for deployment or for testing other polymec-based libs.
    paths:
      - $(find polymec | tr "\n" ":")

  s3_region: "us-west-2"

script: 
  - make config debug=$DEBUG mpi=$MPI prefix=polymec && make -j4 debug=$DEBUG mpi=$MPI install

