language: c

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - cmake
    - libopenmpi-dev
    - gfortran

script: 
  - make config debug=1 mpi=0 && make debug=1 mpi=0
  - make config debug=0 mpi=0 && make debug=0 mpi=0
  - make config debug=1 mpi=1 && make debug=1 mpi=1
  - make config debug=0 mpi=1 && make debug=0 mpi=1

