language: c

sudo: required

os:
  - linux
  - osx

dist: trusty # Ubuntu 14.04.

compiler:
  - clang
  - gcc

env:
  - DEBUG=0 MPI=0 SHARED=0
  - DEBUG=0 MPI=0 SHARED=1
  - DEBUG=0 MPI=1 SHARED=0
  - DEBUG=0 MPI=1 SHARED=1
  - DEBUG=1 MPI=0 SHARED=0
  - DEBUG=1 MPI=0 SHARED=1
  - DEBUG=1 MPI=1 SHARED=0
  - DEBUG=1 MPI=1 SHARED=1

install: sh ./.travis/install-$TRAVIS_OS_NAME-deps.sh

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: polymec-dev.travis-ci
  region: us-west-2
  skip_cleanup: true
  local_dir: $HOME/latest
  upload-dir: polymec-dev
  acl: public_read

script: 
  - make config debug=$DEBUG mpi=$MPI shared=$SHARED prefix=$HOME/polymec-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED
  - make -j4 debug=$DEBUG mpi=$MPI shared=$SHARED install 
  - make debug=$DEBUG mpi=$MPI shared=$SHARED test

after_success: 
  - cd $HOME
  - mkdir -p latest 
  - tar czvf polymec-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED.tar.gz polymec-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED/* 
  - mv polymec-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED.tar.gz latest

after_failure: 
  - cat build/*/Testing/Temporary/LastTest.log
