language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install -qq libopenmpi-dev

script: 
  - make config debug=1 mpi=0 && make debug=1 mpi=0
  - make config debug=0 mpi=0 && make debug=0 mpi=0
  - make config debug=1 mpi=1 && make debug=1 mpi=1
  - make config debug=0 mpi=1 && make debug=0 mpi=1

