language: c

sudo: required

dist: trusty # Ubuntu 14.04.

compiler:
  - clang
  - gcc

env:
  - DEBUG=0 MPI=0
  - DEBUG=0 MPI=1
  - DEBUG=1 MPI=0
  - DEBUG=1 MPI=1

addons:
  apt:
    # Travis whitelist of packages.
    # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    packages:
      - cmake
      - gcc
      - clang
      - libopenmpi-dev
      - gfortran

  deploy:
    provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_KEY
    bucket: polymec-dev.travis-ci
    region: us-west-2
    skip_cleanup: true
    local_dir: $HOME/latest
    upload-dir: polymec-dev
    acl: public_read

#  artifacts:
#    # We stick build artifacts onto Amazon S3 so that they can be retrieved 
#    # either for deployment or for testing other polymec-based libs.
#    paths:
#      - $HOME/polymec-$CC-debug=$DEBUG-mpi=$MPI.tar.gz
#
#    s3_region: us-west-2

    #debug: true

after_success: 
  - cd $HOME
  - mkdir -p latest 
  - tar czvf polymec-$CC-debug=$DEBUG-mpi=$MPI.tar.gz polymec-$CC-debug=$DEBUG-mpi=$MPI/* 
  - mv polymec-$CC-debug=$DEBUG-mpi=$MPI.tar.gz latest

script: 
  - make config debug=$DEBUG mpi=$MPI prefix=$HOME/polymec-$CC-debug=$DEBUG-mpi=$MPI && make -j4 debug=$DEBUG mpi=$MPI install

